language: ruby
rvm:
  - 2.2
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: fBY8nWttRTNvD1AdU9+ZNa7CODLljATiEqfHXXvYCZsJhPgH8Ht0SMqOKCQEzbqIrjIMEy38TWhXFRrvLfnBAwCAL1U9AZY9bNpJK7BIGd7qaIsCL0iVssRJPLvw0O1ZBvzE9ppwhsv+UQc6F0YtzRBZ5+eNoEREiywXX5gVus9xWkrni2BL3mbaoXAc9IuIkulVuFXZOTOK/ZPPkvEJ2WTynhLjEAZv0+ctWdrbo02cfwh8dpgnQ4+jH97s3erLO146AySNibkJpf0DsQHwF+mn6FoCGsLmDsMpomU52HYQz5V/RHYHjijqXrr39EwOh/wVP/MhlvYKGWSfBurixcXcHFxfT2MeNmeuvpp9n8R5q82ZqFZ7eqJS1K+aTE8O5EBWnHmy7GVPkfO0NiZnllYKlynJI9njF0060Zbj7uEl8NTHa6zdlEm8lCNHV5anlcNAIFffW8yImCGLgyevalhPGy/Sq/zeFNYyPKRxAlot7FdUuIoAINRxgo0/jupc8hMCEz5/oTY3jZGVdfIFnMHde5tSZG2sb8xCy0owvvCZ/0nDtLYWxrdVyw/mwT6YUrRUdCgPACCV9Qd/Wc21+8EJ1EjXbZvNLXgtM/nmHIoneRlBFpIIrEBVc9h6R7dqwo9NuoLfdOGNxvbHxi7AxguL7/E4GFcdRrlRELqPht8=
  gem: job_notifier
  on:
    tags: true
    repo: platanus/job_notifier
